# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b0b4743a8c5ca3aeb2e74bb692bb6ab6ea1c6fc704f378da387c1f2891bec93173f5cd6d8bcfa27e2c0c2992ff740160e548ad12b4a250679a6f42250fd1240

test:
  secret_key_base: 2924817fa3d42f65b287aa905a57e2571bf92529214ef9d256ddbb97bf5f12071e90f7197324f602dd1603a88d3b7e49eaeab174c2b648e07a5fcd8f4252f337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
